version: '3.0'

# PRODUCTION

services:
  gonemapi:
    image: eu.gcr.io/gonema/gonemapi:latest
    container_name: gonemapi
    build:
      context: ./
      dockerfile: ./cmd/visualResourceServer/Dockerfile

  gonemaweb:
    image: eu.gcr.io/gonema/gonemaweb:latest
    container_name: gonemaweb
    build:
      context: ./
      dockerfile: ./website/Dockerfile
    environment:
      TEMPLATES_DIR: website/templates
      STATIC_ASSET_DIR: website/static
      GONEMAPI_HOST: https://gonemapi.ruggieri.tech
      GONEMAES_API_HOST: http://gonemaes_api
    restart: always

  gonemaes_server:
    image: eu.gcr.io/gonema/gonemaes_server:latest
    container_name: gonemaes_server
    build:
      context: ./
      dockerfile: ./pkg/database/elastic/Dockerfile
    environment:
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 8000:9200

  gonemaes_api:
    image: eu.gcr.io/gonema/gonemaes_api:latest
    container_name: gonemaes_api
    build:
      context: ./
      dockerfile: cmd/elasticSearchServer/Dockerfile
    environment:
      - GONEMAES_HOST=https://gonemaeserver.ruggieri.tech
      - GONEMAES_PORT=9200

  gonemakib:
    image: docker.elastic.co/kibana/kibana:7.4.0
    container_name: gonemakib
    environment:
      SERVER_NAME: gonemakib
      ELASTICSEARCH_HOSTS: https://gonemaeserver.ruggieri.tech:8000
    ports:
      - 5601:5601

volumes:
  esdata01:
    driver: local
networks:
  esnet: