version: '3.0'

services:
  gonemapi:
    image: eu.gcr.io/gonema/gonemapi:latest
    build:
      context: ./
      dockerfile: ./cmd/visualResourceServer/Dockerfile
    ports:
      - 8080:8080

  gonemaweb:
    image: eu.gcr.io/gonema/gonemaweb:latest
    build:
      context: ./
      dockerfile: ./website/Dockerfile
    ports:
      - 8080:8080

#  test:
        ##    image: test
        ##    build:
        ##      context: .
        ##      dockerfile: testing/Dockerfile
        ##    ports:
        ##      - 8080:8080
        ##    volumes:
      ##      - ./testing:/go/testing
      ##      - ./prova:/go/prova