version: '3.0'

# PRODUCTION

services:
  gonemapi:
    image: eu.gcr.io/gonema/gonemapi:latest
    build:
      context: ./
      dockerfile: ./cmd/visualResourceServer/Dockerfile

  gonemaweb:
    image: eu.gcr.io/gonema/gonemaweb:latest
    build:
      context: ./
      dockerfile: ./website/Dockerfile
    environment:
      - TEMPLATES_DIR=website/templates
      - STATIC_ASSET_DIR=website/static
      - GONEMAPI_HOST=https://gonemapi.ruggieri.tech
    restart: always