version: '3.0'

services:
  gonemapi:
    image: eu.gcr.io/gonema/gonemapi:latest
    build:
      context: ./
      dockerfile: ./cmd/visualResourceServer/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./pkg:/visualResourceServer/pkg
      - ./cmd/visualResourceServer:/visualResourceServer/cmd/visualResourceServer
      - ./configs:/visualResourceServer/configs

  gonemaweb:
    image: eu.gcr.io/gonema/gonemaweb:latest
    build:
      context: ./
      dockerfile: ./website/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./pkg:/web/pkg
      - ./website:/web/website
      - ./configs:/web/configs

#  test:
        ##    image: test
        ##    build:
        ##      context: .
        ##      dockerfile: testing/Dockerfile
        ##    ports:
        ##      - 8080:8080
        ##    volumes:
      ##      - ./testing:/go/testing
      ##      - ./prova:/go/prova