version: '3.0'

# PRODUCTION

services:
  gonemaweb:
    image: eu.gcr.io/gonema/gonemaweb:latest
    container_name: gonemaweb
    build:
      context: ./
      dockerfile: ./website/Dockerfile
    environment:
      TEMPLATES_DIR: website/templates
      STATIC_ASSET_DIR: website/static
      GONEMAES_API_HOST: https://gonemaes_api.ruggieri.tech
      GONEMAES_API_PORT: 8080
      #OMDB_APIKEY:
    restart: always