version: '3.0'

# DEVELOPMENT

services:
  gonemaweb:
    ports:
      - 8080:8080
    hostname: gonemaweb
    volumes:
      - ./pkg:/web/pkg
      - ./website:/web/website
      - ./configs:/web/configs
    environment:
      GONEMAES_API_HOST: http://gonemaes_api
      GONEMAES_API_PORT: 8080
    networks:
      - gonemadb_esnet

networks:
  gonemadb_esnet:
    external: true